production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/default
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: localhost
    port: 8984
    log_level: INFO
    path: /solr/default
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test

